### ISSUE TITLE
[BUG] rotate issue

### ISSUE THREAD

**Issue by IceWaffles** [Niestrat99/AT-Rewritten#110]
### Reproducing
Steps to reproduce the behaviour:
1. Go to config.yml
2. Have your settings like this: 
# Whether or not teleportation should be cancelled if the player rotates or moves.
cancel-warm-up-on-rotation: false

# Whether or not teleportation should be cancelled upon movement only.
cancel-warm-up-on-movement: true
3. Restart server and do a teleport (eg /spawn), if you rotate even on warmup it cancels.

### Expected Behaviour
For it not to cancel if you rotate

### Server
Use /version to fill out the following information.
 - Server Type: [Purpur]
 - Server Version: [1.20.1]
 - Build (where applicable): [2015]

### Plugin Information
5.6.12

**Comment by Thatsmusic99** [comment]
Haven't had any luck reproducing on the same server type and versions, are you able to confirm the config is being saved? Are you able to send the file here?

**Comment by IceWaffles** [comment]
I can confirm both. This could just be a false report from a random player. Anyways, I did update it to 6.0 rc2 and apparently it's working fine now? Yet again, I have had no confirmation that it *wasn't* actually working before.
