### ISSUE TITLE
[BUG] New players tp disabled

### ISSUE THREAD

**Issue by IceWaffles** [Niestrat99/AT-Rewritten#116]
### Description
New players who have just joined have their tp disabled, yet when they rejoin it works

### Reproducing
Steps to reproduce the behaviour:
1. Have a new player join whilst running https://github.com/Niestrat99/AT-Rewritten/actions/runs/5597165577 makes them have their TPs off by default
2. If they rejoin, it seems to work again

### Expected Behaviour
For new players and all players to have to requests on by default

### Server
Use /version to fill out the following information.
 - Server Type: [Purpur]
 - Server Version: [1.20.1]
 - Build (where applicable): [2018]

### Plugin Information
https://github.com/Niestrat99/AT-Rewritten/actions/runs/5597165577

**Comment by Thatsmusic99** [comment]
May be unable to do a lot about this for the next week but does https://github.com/Niestrat99/AT-Rewritten/actions/runs/5654967298/job/15319103462 fix it (when it compiles)?

**Comment by Thatsmusic99** [comment]
Did just try with the latest compiled version of AT and it no longer seems to be an issue, so I'll be closing this issue, feel free to reopen if the issue persists.
