### ISSUE TITLE
[BUG] tpofflhere does not work between different dimensions

### ISSUE THREAD

**Issue by Ze-4** [Niestrat99/AT-Rewritten#125]
when a player is logged out in a different dimension that the player running /tpofflhere the offline player will be teleported to the coordinates of the player running the command, but will not switch dimensions.

Steps to reproduce the behaviour:
1. have a player log out in the nether
2. try to teleport them to spawn in the overworld with /tpofflhere
3. have them log in
4. They will still be in the nether, at the exact coordinates of the player running the command. 

### Server
Use /version to fill out the following information.
 - Server Type: [Purpur] (should still work on paper)
 - Server Version: [1.20.1]
 - Build (latest)

### Plugin Information
Use /version AdvancedTeleport to fill out this information.
- Plugin version: [5.6.14]

**Comment by Thatsmusic99** [comment]
For the unaware, this was fixed pre-emptively in the following builds:
- [v5 #158](https://ci.pluginwiki.us/job/Advanced%20Teleport/158/)
- [v6 #57](https://github.com/Niestrat99/AT-Rewritten/actions/runs/6971063652)

Will be closed when individual builds have been released on sites

**Comment by Thatsmusic99** [comment]
Since v6 has been released in all public channels with the resolved issue, I'll close this now.
