### ISSUE TITLE
[BUG] Form messages never used

### ISSUE THREAD

**Issue by HaHaWTH** [Niestrat99/AT-Rewritten#131]
### Description
When generating a new configuration, there's bedrock form related messages in the file. But it is not being used

### Reproducing
Steps to reproduce the behaviour:
1. Install latest v6 version of AT
2. Start the server
3. See form messages in custom_message.yml

### Expected Behaviour
Will bedrock form support being added in the future(That could be nice)? Or this is unused

### Server
Use /version to fill out the following information.
 - Server Type: Paper
 - Server Version: 1.20.6/1.21

### Plugin Information
Use /version AdvancedTeleport to fill out this information.
- Plugin version: 6.1.1

**Comment by Thatsmusic99** [comment]
It has been implemented; you do need to enable the feature in the config.yml, have you verified that it is enabled? (It should be under miscellaneous)

**Comment by HaHaWTH** [comment]
I enabled bedrock forms in the config.yml, but when I type /homes and /tpa, the form didn't show up. I did configure floodgate settings correctly. :/

**Comment by Thatsmusic99** [comment]
I'll take a look into it later, I was going to mention the send-floodgate-data option but saw you'd been here before, so I assume that you already have it enabled :) it's entirely possible that AT isn't up to date with Geyser/Floodgate and just needs a boost.

**Comment by Thatsmusic99** [comment]
Found the cause of this one - just turned out some login code was assigning Bedrock players to the same status that Java players would have. Once it's ready, you can download a fixed build under the "Artefacts" section here: https://github.com/Niestrat99/AT-Rewritten/actions/runs/9783618260

Download and unzip the file, then there's a jar you can use there.

**Comment by HaHaWTH** [comment]
> Found the cause of this one - just turned out some login code was assigning Bedrock players to the same status that Java players would have. Once it's ready, you can download a fixed build under the "Artefacts" section here: https://github.com/Niestrat99/AT-Rewritten/actions/runs/9783618260
> 
> Download and unzip the file, then there's a jar you can use there.

Thanks so much🥰
