### ISSUE TITLE
How to disable multiple pending requests?

### ISSUE THREAD

**Issue by Cretezy** [Niestrat99/AT-Rewritten#33]
I could not find any options related to disable multiple pending requests. Is this something that is supported or planned?

**Comment by Thatsmusic99** [comment]
Currently not an implemented feature, can look into making it toggleable.

**Comment by Cretezy** [comment]
Ideally, would be nice to have a toggle to allow only a single requests
(creating a new request should cancel the previous).

Additionally, random TPs shouldn't create a new request if there's already
one pending, since a user could spam right click a sign (this should be by
default, not affected by toggle)

**Comment by Thatsmusic99** [comment]
Will look into that as well tonight, but it'll be considered a separate issue.

**Comment by Cretezy** [comment]
Makes sense. I can help with code/debug if you want.

**Comment by Thatsmusic99** [comment]
Very proud to say I accidentally battered my server stress testing this one. :)

I'll be releasing a snapshot shortly for the bug you mentioned so you can mess with that if you wish to. I still have a few amendments to make to this version before intending on a full release.

**Comment by Thatsmusic99** [comment]
[/tpr has been patched in v5.4.6-SNAPSHOT-2.](https://github.com/Niestrat99/AT-Rewritten/releases/tag/v5.4.6-SNAPSHOT-2) The actual enhancement this issue covers though I'll look into fully covering when I next get the opportunity (maybe tomorrow if I'm not too tired from the extra hours in school).

**Comment by Thatsmusic99** [comment]
Added in [v5.4.6-SNAPSHOT-3](https://github.com/Niestrat99/AT-Rewritten/releases/tag/v5.4.6-SNAPSHOT-3) but haven't been able to test it because I don't have three accounts to poke it with, unfortunately. If you have the opportunity to test it or need me, please let me know!

**Comment by Cretezy** [comment]
Message me on Discord and we can test: Cretezy#3769

**Comment by Thatsmusic99** [comment]
Request sent. :)

**Comment by Thatsmusic99** [comment]
This feature was added in v5.4.6, so this issue can be closed.
