### ISSUE TITLE
[BUG] Help HomesCommand not working

### ISSUE THREAD

**Issue by LucasMucGH** [Niestrat99/AT-Rewritten#35]
### Description
If you use `/athelp HomesCommand` nothing happens. Every other help command works

### Reproducing
1. Use `/athelp HomesCommand` ingame
2. Nothing happens - not even an error gets thrown

### Expected Behaviour
A list of the commands regarding home teleportation

### Server
 - Server Type: Paper
 - Server Version: 1.16.5
 - Build: 586

### Plugin Information
- Plugin version: 5.4.7

**Comment by Thatsmusic99** [comment]
That would be a typo, try `/athelp homes` instead.
