### ISSUE TITLE
[BUG] Geyser Players look and it's counted as moving

### ISSUE THREAD

**Issue by Romvnly-Gaming** [Niestrat99/AT-Rewritten#44]
### Description
Geyser Players look and it's counted as moving when teleporting. I look around a bit on Bedrock, and it's counted as moving.

### Reproducing
1. turn off look around in config and make sure cancel on move is true
2. do a command that requires u to stand still (you can still look around without it being canceled)
3. look around, maybe a 90 degree turn in where you're looking
4. teleport canceled

### Expected Behaviour
I hope that bedrock can look around while 

### Screenshots
N/A, I believe my exemption in the reproducing section should suffice.

### Stacktraces
N/A

### Server
Use /version to fill out the following information.
 - Server Type: Purpur (Paper fork)
 - Server Version: 1.16.5
 - Build (where applicable): 1090

### Plugin Information
Use /version AdvancedTeleport to fill out this information.
- Plugin version: 5.4.7+DEV_15

### Additional Information
N/A

**Comment by Thatsmusic99** [comment]
Can I ask if you did /atreload at any point between steps 1 and 2? I'm afraid I can't test this properly until Saturday at the earliest.

**Comment by Romvnly-Gaming** [comment]
No, I did not.

**Comment by Thatsmusic99** [comment]
Please retry then with /atreload since the configuration cannot reload without it, and inform me of the results. Thanks in advance!

**Comment by Romvnly-Gaming** [comment]
Actually, this has been my server's config for multiple restarts now. I didn't just change the setting.

**Comment by Thatsmusic99** [comment]
In that case, I'll test this when I get the opportunity. Will leave this open until I can confirm it.

**Comment by Thatsmusic99** [comment]
Just got the opportunity to test this.

Unfortunately, I could not reproduce the bug on the following versions (Geyser being the latest build from the 5th June):
![](https://i.gyazo.com/6d314707c6d3902901f206c70f8a9c7a.png)

`cancel-warm-up-on-rotation` confirmed to be set to false whilst `cancel-warm-up-on-movement` set to true, with /atreload run before joining the server.

**Comment by Romvnly-Gaming** [comment]
Interesting, the issue is no longer persisting for me either on the latest Geyser. Closing.
