### ISSUE TITLE
Use command alias for essentials-like commands

### ISSUE THREAD

**Issue by quiquelhappy** [Niestrat99/AT-Rewritten#56]
Hello, I'd like to use tpaccept and tpdeny, similar to essentials. If we could configure a command alias or you could just provide an static command alias with tpaccept and tpdeny I'd be happy.

Thanks!

**Comment by Thatsmusic99** [comment]
Hello - /tpaccept and /tpdeny are already considered aliases, if not the main name, for AT's /tpa accept/denying commands. What seems to imply otherwise right now? Cheers in advance.

**Comment by quiquelhappy** [comment]
Hello, I had no idea how I tested this. You are right. Sorry for wasting ur time :)
