### ISSUE TITLE
[BUG] Unloaded chunk issue with slab coursing player to go below bedrock

### ISSUE THREAD

**Issue by Thefluffypvper1** [Niestrat99/AT-Rewritten#60]
### Description
When going to a unloaded location with a slab on it you will get pushed past bedrock and dip down 

### Reproducing
Steps to reproduce the behaviour:
1. Sethome at a location on bedrock
2. Place a slab on bedrock
3. Unload the chunk
4. Go to the home location and you will fall past bedrock

### Expected Behaviour
You don't go pot under bedrock and you get teleported to that location with no issues

### Screenshots
[If applicable, add screenshots to help explain your problem.](https://www.youtube.com/watch?v=a8QIRljep8c&ab_channel=Doooch)

### Stacktraces
N/A

### Server
Use /version to fill out the following information.
 - Server Type: Winespigot
 - Server Version: 1.8.8
 - Build where applicable): [200]](https://gyazo.com/c1a538bd3b6281d99f7c0b88e61ef695)

### Plugin Information
Use /version AdvancedTeleport to fill out this information.
- Plugin version: https://gyazo.com/fcd6e46af9a10536d5e9462059bf1c46

### Additional Information
When the player goes into void its another  plugin saving the player

**Comment by Thatsmusic99** [comment]
Not an AT problem. It's just the server loading the chunks. Not much I can really do with this.
