### ISSUE TITLE
Select accept or deny in chat

### ISSUE THREAD

**Issue by Fantom250YT** [Niestrat99/AT-Rewritten#65]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Be able to accept / deny by pressing a tick or cross in chat, shown in image below

**Describe alternatives you've considered**
A config option for those who want to use commands instead

**Additional context**
![image](https://user-images.githubusercontent.com/73852683/150699328-4136dd60-d897-4ba0-a766-c9f5eeafa3bc.png)

**Comment by Thatsmusic99** [comment]
Well, uh, this is already a thing.

What AT version are you on?

**Comment by Fantom250YT** [comment]
Sorry, didn't try it just saw on the description it was only for multiple requests, thanks for the help.
