### ISSUE TITLE
[BUG] Incorrect teleport locations across dimensions

### ISSUE THREAD

**Issue by IceWaffles** [Niestrat99/AT-Rewritten#90]
### Reproducing
Steps to reproduce the behaviour:
1. Go to the end
2. Build a small box 2 blocks high 
3. Go inside
4. Have someone /tpa to you **from the overworld**
5. Accept, and they'll be on top of instead of in the box you built

### Expected Behaviour
They teleport to you even when going cross dimension and not on top of the blocks/house you're in. 

### Server
git-PufferfishPlus-12 (MC: 1.19.2)*
(Latest version)

### Plugin Information
AdvancedTeleport version 5.6.4

### Note
It *seems* fine when going from end -> overworld but I have done no extensive testing. I have not tested homes either but I suspect this will likely be a issue with that as well.

**Comment by Thatsmusic99** [comment]
https://gyazo.com/a18a809e228a92f3d6193134375042de - I didn't have any luck reproducing, does this happen on Paper 1.19.2 and what does the box you made look like?

**Comment by IceWaffles** [comment]
Very odd, it worked for me a couple times. I'll close this for now
