### ISSUE TITLE
[BUG] Moving Homes

### ISSUE THREAD

**Issue by IceWaffles** [Niestrat99/AT-Rewritten#92]
### Description
If you have `overwrite-sethome: true` and already have your max amount of homes set, you can't move a home even if you set one with same name. 

### Reproducing
Steps to reproduce the behaviour:
1. Turn on `overwrite-sethome` in the config.
2. (Let's say you have permission to set 5 homes) Set 5 homes, and name one of these homes `test`.
3. Go to another location and do `/sethome test`
4. It should move the home 'test' to your new location, but instead it reads 'You can't set any more homes!'

### Expected Behaviour
Home 'test' is moved to your new location, as you're moving a existing home elsewhere and not setting a 'new' one. Obviously, if you set a home with a different name than a home you already have, you will be denied and the message output above should be sent.

### Server
git-PufferfishPlus-12 (MC: 1.19.2)*
You are on the latest version!

### Plugin Information
AdvancedTeleport version 5.6.4

### Additional Information
You can technically circumvent this by deleting home `test` and then resetting your home `test` somewhere else. Thus, this isn't a crucial bug to fix. Also, sorry for reporting so much lol

**Comment by Geolykt** [comment]
I can attest this behaviour and it is kind annoying

**Comment by Thatsmusic99** [comment]
Was resolved by Geolykt in this developer build: https://ci.pluginwiki.us/job/Advanced%20Teleport/111/

**Comment by IceWaffles** [comment]
<img width="670" alt="Screenshot 2022-11-30 at 5 32 31 PM" src="https://user-images.githubusercontent.com/86599175/204867767-f53c5a5e-03af-49ca-942c-8edc74b6d36a.png">

Which build am I meant to use?

**Comment by Niestrat99** [comment]
The file you want to download is the top one.
